image: Ubuntu2204

branches:
  only:
    - main

environment:
  matrix:
    - nodejs_version: "18.12.0"

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install $nodejs_version
  - nvm use $nodejs_version
  - echo "Node.js version:"
  - node --version
  - echo "NVM version:"
  - nvm --version

install:
  - echo "Installing dependencies..."
  - yarn install

build_script:
  - echo "Building the project..."
  - yarn build

artifacts:
  - path: dist
    name: artifact

deploy_script:
  - echo "Configuring Git..."
  - git config --global credential.helper store
  - git config --global user.name "Roman9456"
  - git config --global user.email "smolyakov_ra@mail.ru"
  - echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - git clone --branch gh-pages https://github.com/Roman9456/collapse.git gh-pages
  - rm -rf gh-pages/*
  - cp -r dist/* gh-pages/
  - cd gh-pages
  - git add .
  - git diff-index --quiet HEAD || git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
  - echo "Deployment complete."